### ISSUE TITLE
Need a placeholder to preserve styling on the pet photos

### ISSUE THREAD

**Issue by ADKebert** [ctscodes/petrescue#4]
The current pet photos look great, but I think there should be a placeholder in case the number of actual adoptable pets doesn't evenly divide by 3.

I think it would still look ok if it were just blank space so long as the formatting and responsiveness is preserved.  Bonus points if they aren't displayed when the layout switches to single column

**Comment by bam1056** [comment]
Dynamically updated based on current pets on Petfinder, placeholders will exist when there are less than 6 pets. If more than 6, user must follow the link to see all available pets on petfinder
